"""Initial production schema (DATABASE_SCHEMA.md sections 1-2.19).

Executed as raw DDL rather than autogenerated from ORM models: this is the
schema as designed and reviewed in docs/DATABASE_SCHEMA.md, and the migration
is the authoritative, versioned record of it. E0 wires up ORM models + real
application logic only for the auth-relevant tables (roles, permissions,
role_permissions, users, refresh_tokens) per ROADMAP.md's E0 scope; the
remaining tables exist here as real, executable schema ahead of the features
that will use them in E1+ -- this is standard "migrate schema first, build
features incrementally" practice, not placeholder application code.

Research-extension tables (DATABASE_SCHEMA.md §2.20) are out of scope for
this migration; they land in the R0 migration per ROADMAP.md.

Revision ID: 0001
Revises:
Create Date: 2026-07-12
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Extensions ---
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")  # gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")  # case-insensitive email

    # --- 2.1 roles ---
    op.execute("""
        CREATE TABLE roles (
            id              SMALLSERIAL PRIMARY KEY,
            name            VARCHAR(50)  NOT NULL UNIQUE,
            description     TEXT,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)

    # --- 2.2 permissions / role_permissions ---
    op.execute("""
        CREATE TABLE permissions (
            id              SMALLSERIAL PRIMARY KEY,
            code            VARCHAR(100) NOT NULL UNIQUE,
            description     TEXT
        )
    """)
    op.execute("""
        CREATE TABLE role_permissions (
            role_id         SMALLINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
            permission_id   SMALLINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
            PRIMARY KEY (role_id, permission_id)
        )
    """)

    # --- 2.3 users ---
    op.execute("""
        CREATE TABLE users (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            email               CITEXT NOT NULL UNIQUE,
            hashed_password     VARCHAR(255) NOT NULL,
            full_name           VARCHAR(150) NOT NULL,
            role_id             SMALLINT NOT NULL REFERENCES roles(id),
            is_active           BOOLEAN NOT NULL DEFAULT true,
            mfa_enabled         BOOLEAN NOT NULL DEFAULT false,
            mfa_secret_encrypted BYTEA,
            failed_login_count  SMALLINT NOT NULL DEFAULT 0,
            locked_until        TIMESTAMPTZ,
            last_login_at       TIMESTAMPTZ,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX idx_users_role_id ON users(role_id)")

    # --- 2.4 refresh_tokens ---
    op.execute("""
        CREATE TABLE refresh_tokens (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            token_hash      VARCHAR(255) NOT NULL,
            device_info     VARCHAR(255),
            ip_address      INET,
            issued_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at      TIMESTAMPTZ NOT NULL,
            revoked_at      TIMESTAMPTZ
        )
    """)
    op.execute("CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id)")
    op.execute("CREATE UNIQUE INDEX idx_refresh_tokens_hash ON refresh_tokens(token_hash)")

    # --- 2.5 api_keys ---
    op.execute("""
        CREATE TABLE api_keys (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name            VARCHAR(100) NOT NULL,
            key_prefix      VARCHAR(12) NOT NULL,
            key_hash        VARCHAR(255) NOT NULL,
            scopes          TEXT[] NOT NULL DEFAULT '{}',
            last_used_at    TIMESTAMPTZ,
            expires_at      TIMESTAMPTZ,
            revoked_at      TIMESTAMPTZ,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX idx_api_keys_user_id ON api_keys(user_id)")

    # --- 2.6 mitre_techniques ---
    op.execute("""
        CREATE TABLE mitre_techniques (
            id              VARCHAR(10) PRIMARY KEY,
            parent_id       VARCHAR(10) REFERENCES mitre_techniques(id),
            name            VARCHAR(200) NOT NULL,
            tactic          VARCHAR(100) NOT NULL,
            url             TEXT,
            version_imported VARCHAR(20) NOT NULL
        )
    """)
    op.execute("CREATE INDEX idx_mitre_tactic ON mitre_techniques(tactic)")

    # --- 2.7 detection_rules ---
    op.execute("CREATE TYPE rule_status AS ENUM ('draft', 'in_review', 'approved', 'rejected', 'deployed', 'deprecated')")
    op.execute("CREATE TYPE rule_severity AS ENUM ('informational', 'low', 'medium', 'high', 'critical')")
    op.execute("""
        CREATE TABLE detection_rules (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            rule_uid            VARCHAR(64) NOT NULL UNIQUE,
            title               VARCHAR(200) NOT NULL,
            description         TEXT,
            status              rule_status NOT NULL DEFAULT 'draft',
            severity            rule_severity NOT NULL DEFAULT 'medium',
            log_source          VARCHAR(100),
            tags                TEXT[] NOT NULL DEFAULT '{}',
            owner_id            UUID NOT NULL REFERENCES users(id),
            current_version_id  UUID,
            is_ai_generated     BOOLEAN NOT NULL DEFAULT false,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX idx_rules_status ON detection_rules(status)")
    op.execute("CREATE INDEX idx_rules_owner ON detection_rules(owner_id)")
    op.execute("CREATE INDEX idx_rules_tags ON detection_rules USING GIN(tags)")

    # --- 2.8 detection_rule_versions ---
    op.execute("""
        CREATE TABLE detection_rule_versions (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            rule_id         UUID NOT NULL REFERENCES detection_rules(id) ON DELETE CASCADE,
            version_number  INTEGER NOT NULL,
            sigma_yaml      TEXT NOT NULL,
            change_summary  TEXT,
            created_by      UUID NOT NULL REFERENCES users(id),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (rule_id, version_number)
        )
    """)
    op.execute("CREATE INDEX idx_rule_versions_rule_id ON detection_rule_versions(rule_id)")
    op.execute("""
        ALTER TABLE detection_rules
            ADD CONSTRAINT fk_current_version
            FOREIGN KEY (current_version_id) REFERENCES detection_rule_versions(id)
    """)

    # --- 2.9 rule_mitre_mapping ---
    op.execute("""
        CREATE TABLE rule_mitre_mapping (
            rule_id         UUID NOT NULL REFERENCES detection_rules(id) ON DELETE CASCADE,
            technique_id    VARCHAR(10) NOT NULL REFERENCES mitre_techniques(id),
            PRIMARY KEY (rule_id, technique_id)
        )
    """)
    op.execute("CREATE INDEX idx_mapping_technique ON rule_mitre_mapping(technique_id)")

    # --- 2.10 rule_approvals ---
    op.execute("CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected', 'changes_requested')")
    op.execute("""
        CREATE TABLE rule_approvals (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            rule_version_id     UUID NOT NULL REFERENCES detection_rule_versions(id) ON DELETE CASCADE,
            approver_id         UUID NOT NULL REFERENCES users(id),
            status              approval_status NOT NULL DEFAULT 'pending',
            comments            TEXT,
            decided_at          TIMESTAMPTZ,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT chk_no_self_approval CHECK (true)
        )
    """)
    op.execute("CREATE INDEX idx_approvals_version ON rule_approvals(rule_version_id)")

    # --- 2.11 sample_datasets ---
    op.execute("CREATE TYPE dataset_source_type AS ENUM ('sysmon', 'splunk_export', 'elastic_export', 'generic_json', 'cloudtrail')")
    op.execute("""
        CREATE TABLE sample_datasets (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name            VARCHAR(150) NOT NULL,
            source_type     dataset_source_type NOT NULL,
            object_key      TEXT NOT NULL,
            size_bytes      BIGINT NOT NULL,
            event_count     INTEGER,
            uploaded_by     UUID NOT NULL REFERENCES users(id),
            uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX idx_datasets_uploaded_by ON sample_datasets(uploaded_by)")

    # --- 2.12 validation_runs ---
    op.execute("CREATE TYPE validation_status AS ENUM ('queued', 'running', 'succeeded', 'failed')")
    op.execute("""
        CREATE TABLE validation_runs (
            id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            rule_version_id         UUID NOT NULL REFERENCES detection_rule_versions(id) ON DELETE CASCADE,
            dataset_id              UUID NOT NULL REFERENCES sample_datasets(id),
            target_backend          VARCHAR(20) NOT NULL,
            status                  validation_status NOT NULL DEFAULT 'queued',
            matched_event_count     INTEGER,
            execution_time_ms       INTEGER,
            error_message           TEXT,
            results_sample          JSONB,
            executed_by             UUID NOT NULL REFERENCES users(id),
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            completed_at            TIMESTAMPTZ
        )
    """)
    op.execute("CREATE INDEX idx_validation_rule_version ON validation_runs(rule_version_id)")

    # --- 2.13 siem_integrations ---
    op.execute("CREATE TYPE siem_type AS ENUM ('splunk', 'elastic')")
    op.execute("""
        CREATE TABLE siem_integrations (
            id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name                        VARCHAR(100) NOT NULL,
            type                        siem_type NOT NULL,
            base_url                    TEXT NOT NULL,
            encrypted_credentials       BYTEA NOT NULL,
            credentials_key_version     SMALLINT NOT NULL,
            status                      VARCHAR(20) NOT NULL DEFAULT 'untested',
            last_checked_at             TIMESTAMPTZ,
            created_by                  UUID NOT NULL REFERENCES users(id),
            created_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)

    # --- 2.14 deployments ---
    op.execute("CREATE TYPE deployment_status AS ENUM ('pending', 'succeeded', 'failed', 'withdrawn')")
    op.execute("""
        CREATE TABLE deployments (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            rule_version_id     UUID NOT NULL REFERENCES detection_rule_versions(id),
            siem_integration_id UUID NOT NULL REFERENCES siem_integrations(id),
            external_rule_id    VARCHAR(255),
            status              deployment_status NOT NULL DEFAULT 'pending',
            error_message       TEXT,
            deployed_by         UUID NOT NULL REFERENCES users(id),
            deployed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            withdrawn_at        TIMESTAMPTZ
        )
    """)
    op.execute("CREATE INDEX idx_deployments_rule_version ON deployments(rule_version_id)")
    op.execute("CREATE INDEX idx_deployments_integration ON deployments(siem_integration_id)")

    # --- 2.15 false_positive_reports ---
    op.execute("CREATE TYPE fp_resolution_status AS ENUM ('open', 'confirmed_fp', 'confirmed_tp', 'wont_fix')")
    op.execute("""
        CREATE TABLE false_positive_reports (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            rule_id             UUID NOT NULL REFERENCES detection_rules(id) ON DELETE CASCADE,
            deployment_id       UUID REFERENCES deployments(id),
            reported_by         UUID NOT NULL REFERENCES users(id),
            description         TEXT,
            resolution_status   fp_resolution_status NOT NULL DEFAULT 'open',
            resolved_by         UUID REFERENCES users(id),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            resolved_at         TIMESTAMPTZ
        )
    """)
    op.execute("CREATE INDEX idx_fp_rule_id ON false_positive_reports(rule_id)")

    # --- 2.16 alert_investigations ---
    op.execute("""
        CREATE TABLE alert_investigations (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            rule_id             UUID NOT NULL REFERENCES detection_rules(id),
            deployment_id       UUID REFERENCES deployments(id),
            siem_alert_id       VARCHAR(255),
            raw_alert_redacted  JSONB NOT NULL,
            ai_summary          TEXT,
            status              VARCHAR(20) NOT NULL DEFAULT 'new',
            created_by          UUID REFERENCES users(id),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX idx_alert_inv_rule ON alert_investigations(rule_id)")

    # --- 2.17 ai_interactions ---
    op.execute("CREATE TYPE ai_interaction_type AS ENUM ('rule_generation', 'rule_refinement', 'alert_summary', 'quality_recommendation')")
    op.execute("""
        CREATE TABLE ai_interactions (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id             UUID NOT NULL REFERENCES users(id),
            interaction_type    ai_interaction_type NOT NULL,
            related_rule_id     UUID REFERENCES detection_rules(id),
            input_context_hash  VARCHAR(64) NOT NULL,
            model_used          VARCHAR(50) NOT NULL,
            output_text         TEXT NOT NULL,
            tokens_used         INTEGER,
            latency_ms          INTEGER,
            accepted_by_user    BOOLEAN,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX idx_ai_interactions_user ON ai_interactions(user_id)")
    op.execute("CREATE INDEX idx_ai_interactions_type ON ai_interactions(interaction_type)")

    # --- 2.18 coverage_snapshots ---
    op.execute("""
        CREATE TABLE coverage_snapshots (
            id                  BIGSERIAL PRIMARY KEY,
            technique_id        VARCHAR(10) NOT NULL REFERENCES mitre_techniques(id),
            computed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            approved_rule_count INTEGER NOT NULL DEFAULT 0,
            deployed_rule_count INTEGER NOT NULL DEFAULT 0,
            avg_fp_rate         NUMERIC(5,4)
        )
    """)
    op.execute("CREATE INDEX idx_coverage_technique_time ON coverage_snapshots(technique_id, computed_at)")

    # --- 2.19 audit_logs ---
    op.execute("""
        CREATE TABLE audit_logs (
            id              BIGSERIAL PRIMARY KEY,
            user_id         UUID REFERENCES users(id),
            action          VARCHAR(100) NOT NULL,
            resource_type   VARCHAR(50),
            resource_id     VARCHAR(100),
            ip_address      INET,
            user_agent      TEXT,
            metadata        JSONB,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX idx_audit_user ON audit_logs(user_id)")
    op.execute("CREATE INDEX idx_audit_action ON audit_logs(action)")
    op.execute("CREATE INDEX idx_audit_created_at ON audit_logs(created_at)")

    # --- Seed data: five RBAC roles (PRD.md §11.1, API_SPECIFICATION.md §14) ---
    op.execute("""
        INSERT INTO roles (name, description) VALUES
            ('admin', 'Full platform access, including user and integration management'),
            ('detection_lead', 'Reviews and approves rules, deploys to SIEM integrations'),
            ('detection_engineer', 'Authors and validates detection rules'),
            ('analyst', 'Reviews alerts, reports false positives'),
            ('researcher', 'Manages the attack corpus and runs sabotage-evaluation experiments')
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS audit_logs")
    op.execute("DROP TABLE IF EXISTS coverage_snapshots")
    op.execute("DROP TABLE IF EXISTS ai_interactions")
    op.execute("DROP TYPE IF EXISTS ai_interaction_type")
    op.execute("DROP TABLE IF EXISTS alert_investigations")
    op.execute("DROP TABLE IF EXISTS false_positive_reports")
    op.execute("DROP TYPE IF EXISTS fp_resolution_status")
    op.execute("DROP TABLE IF EXISTS deployments")
    op.execute("DROP TYPE IF EXISTS deployment_status")
    op.execute("DROP TABLE IF EXISTS siem_integrations")
    op.execute("DROP TYPE IF EXISTS siem_type")
    op.execute("DROP TABLE IF EXISTS validation_runs")
    op.execute("DROP TYPE IF EXISTS validation_status")
    op.execute("DROP TABLE IF EXISTS sample_datasets")
    op.execute("DROP TYPE IF EXISTS dataset_source_type")
    op.execute("DROP TABLE IF EXISTS rule_approvals")
    op.execute("DROP TYPE IF EXISTS approval_status")
    op.execute("DROP TABLE IF EXISTS rule_mitre_mapping")
    op.execute("ALTER TABLE detection_rules DROP CONSTRAINT IF EXISTS fk_current_version")
    op.execute("DROP TABLE IF EXISTS detection_rule_versions")
    op.execute("DROP TABLE IF EXISTS detection_rules")
    op.execute("DROP TYPE IF EXISTS rule_severity")
    op.execute("DROP TYPE IF EXISTS rule_status")
    op.execute("DROP TABLE IF EXISTS mitre_techniques")
    op.execute("DROP TABLE IF EXISTS api_keys")
    op.execute("DROP TABLE IF EXISTS refresh_tokens")
    op.execute("DROP TABLE IF EXISTS users")
    op.execute("DROP TABLE IF EXISTS role_permissions")
    op.execute("DROP TABLE IF EXISTS permissions")
    op.execute("DROP TABLE IF EXISTS roles")
    op.execute("DROP EXTENSION IF EXISTS citext")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
